### ISSUE TITLE
Issue: Invalid transaction type: 106 after Arbitrum update to Nitro

### ISSUE THREAD

**Issue by AoDev** [ConsenSys-archive/ganache#3606] opened 2022-09-02 17:44 UTC
Since Arbitrum updated to Nitro, Ganache crashes immediately when trying to run a fork.

* Ganache version: **7.4.1**

* Command example

```
ganache --chain.chainId 42161 --chain.vmErrorsOnRPCResponse true --wallet.totalAccounts 10 --fork.url https://arb1.arbitrum.io/rpc --miner.blockGasLimit 120000000 --wallet.mnemonic brownie --server.port 8548 --hardfork istanbul
```

* Error
```
Starting RPC server
Error: Invalid transaction type: 106
    at Function.typeOf (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:218734)
    at Function.typeOfRPC (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:218960)
    at Function.fromRpc (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:217659)
    at /Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:90757
    at Array.forEach (<anonymous>)
    at Function.rawFromJSON (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:90586)
    at Fork.initialize (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:108341)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Blockchain.initialize (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:74896)
    at async EthereumProvider.initialize (/Users/.../.nvm/versions/node/v16.14.1/lib/node_modules/ganache/dist/node/1.js:2:161113)

```

**Comment by AoDev** [comment] 2022-09-03 09:10
See this related issue. https://github.com/NomicFoundation/hardhat/issues/2995

> Certain EVM blockchain (e.g. Arbitrum Nitro) have non-standard [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) typed transaction that would prevent hardhat fork from working due to [Error HH604: Error running JSON-RPC server: Unknown transaction type 106](https://github.com/NomicFoundation/hardhat/blob/db1bbcea3c9113f1b9aa2873a1e865c22739384b/packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts#L298-L300)

**Comment by gzeoneth** [comment] 2022-09-04 09:44
It seems that this is fixed in https://github.com/trufflesuite/ganache/pull/3523
wen release?

**Comment by AoDev** [comment] 2022-09-05 06:51
Looks like it, please create a release with the current changes @davidmurdoch   🙂

**Comment by MicaiahReid** [comment] 2022-09-06 16:55
Thanks for the issue @AoDev! We're hoping to have a release for this out this week! 

I'm going to close this issue as a duplicate of #3458 for now. Thank you!

**Closed as completed by MicaiahReid** 2022-09-06 16:55 UTC
