### ISSUE TITLE
evm_increaseTime returns string concatenation if input is hex-encoded

### ISSUE THREAD

**Issue by wolflo** [ConsenSys-archive/ganache#915] opened 2021-07-28 03:12 UTC
`evm_increaseTime` accepts one parameter (the amount of time to jump forward) and returns the total time adjustment. 

When the provided parameter is hex-encoded, the returned total time adjustment is the previous total time adjustment as a string, concatenated with the hex-encoded parameter as a string.

### To reproduce

`ganache-cli --version` -> `Ganache CLI v6.12.2 (ganache-core: 2.13.2)`

run `ganache-cli` and make the following rpc calls:
```
> curl -H "Content-Type: application/json" -X POST --data \
        '{"id":1337,"jsonrpc":"2.0","method":"evm_increaseTime","params":[60]}' \
        http://localhost:8545
{"id":1337,"jsonrpc":"2.0","result":60}

curl -H "Content-Type: application/json" -X POST --data \
        '{"id":1337,"jsonrpc":"2.0","method":"evm_increaseTime","params":["0x60"]}' \
        http://localhost:8545
{"id":1337,"jsonrpc":"2.0","result":"600x60"}
```

While the first call with a decimal-encoded parameter returns 0 + 60, the second call with a hex-encoded parameter returns "60" ++ "0x60".

### Notes
I can not reproduce this directly against the ganache-core test suite. This test case seems like it should cover it, but ganache-cli doesn't have the same behavior.

https://github.com/trufflesuite/ganache-core/blob/5a347b3e66288cbc5b5249f6ce2401a4d66bfb9b/src/chains/ethereum/ethereum/tests/api/evm/evm.test.ts#L69-L76

**Comment by davidmurdoch** [comment] 2021-07-28 04:35
The reason your can't reproduce this in a text case is that the develop branch of the repo is a complete rewrite of ganache; and this big appears to be fixed 😁.

I'm out of office until next week, but hopefully we can look into requesting an alpha version of this rewrite shortly after I get back.

**Comment by wolflo** [comment] 2021-07-28 15:06
Thanks!

**Comment by wolflo** [comment] 2021-07-28 22:45
Just for curiosity's sake, another thing that seems to be fixed on develop:

The units / type for `evm_increaseTime` are scrambled when the argument is a hex string.

### Reproducing

`ganache-cli`
```
❯ curl -H "Content-Type: application/json" -X POST --data \
        '{"id":1337,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true]}' \
        http://localhost:8545 | jq '.result.timestamp'

"0x6101dc5b"

❯ curl -H "Content-Type: application/json" -X POST --data \
        '{"id":1337,"jsonrpc":"2.0","method":"evm_increaseTime","params":["0x5"]}' \
        http://localhost:8545
{"id":1337,"jsonrpc":"2.0","result":"00x5"}

❯ curl -H "Content-Type: application/json" -X POST --data \
        '{"id":1337,"jsonrpc":"2.0","method":"evm_mine","params":[]}' \
        http://localhost:8545
{"id":1337,"jsonrpc":"2.0","result":"0x0"}

❯ curl -H "Content-Type: application/json" -X POST --data \
        '{"id":1337,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true]}' \
        http://localhost:8545 | jq '.result.timestamp'

"0xecd58b437df"
```

The block timestamp hex values in decimal are: 
```
1627511899
16275119290335
```

So, trying to increase the block timestamp by 5 increases it by 16273491778436. This does not happen if the parameter to `evm_increaseTime` is decimal-encoded, and it is fixed on `develop` branch.

**Comment by davidmurdoch** [comment] 2021-08-06 01:39
Closing as i'm just cleaning up issues that are fixed in develop. 7.0.0-alpha release is coming soon(tm)!

**Closed as completed by davidmurdoch** 2021-08-06 01:39 UTC
Labels: bug
