### ISSUE TITLE
evm_setTime doesn't update "pending" block timestamp

### ISSUE THREAD

**Issue by fubuloubu** [ConsenSys-archive/ganache#2618] opened 2022-03-17 03:33 UTC
Writing a ganache plugin for ape, ran into a problem in my test suite for checking updates to the timestamp

See:
https://github.com/ApeWorX/ape-ganache/blob/e0b3b468c6a6721d194969d5bdc4eb95be73eba2/tests/test_ganache.py#L102-L104

**Comment by MicaiahReid** [comment] 2022-03-17 13:51
Thanks for the issue @fubuloubu. I think I'll close this as a duplicate of #772. The deeper issue here is that we don't currently have a real pending block - we just return `block.latest`. Since the latest block has already been mined, it's timestamp is already set. Once we actually have a pending block, the EVM time should have an affect on pending block's timestamp.

**Closed as completed by MicaiahReid** 2022-03-17 13:51 UTC
