### ISSUE TITLE
Ganache-cli still faster (forking bsc on mac m1)

### ISSUE THREAD

**Issue by NikZak** [ConsenSys-archive/ganache#2178] opened 2022-01-25 02:51 UTC
Ok, this is a post of help. I want to figure whether this is just my problem. 
I tried 
ganache-cli
ganache-7-alpha
ganache-7-beta
ganache-7
hardhat

And I always go back to ganache-cli eventually as it is the fastest and most stable and the only one that let a long chain of operations run till the end. I don't know whether the problem is in my config or smth else as ganache is notoriously hard to debug based on the logs alone. 

I'll probably post a config for my ganache-cli and ganache-7 to get feedback if there are any major mistakes. And would be happy to hear anyone else - what is their experience.

ganache-cli
```
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --host 0.0.0.0 -f "https://bsc-dataseed1.defibit.io/" --chainId 1337 --account "smthsmth,100000000000000000000" --account "smthsmth,100000000000000000000"
    ports:
      - "8545:8545"
```
ganache-7
```
  ganache:
    image: trufflesuite/ganache:v7.0.0
    command: --host 0.0.0.0 -f "https://bsc-dataseed1.defibit.io/"  --chain.chainId 1337 --account "smthsmth,100000000000000000000" --account "smthsmth,100000000000000000000"
    ports:
      - "8545:8545"

```

Thank you and any feedback is welcome!

**Comment by davidmurdoch** [comment] 2022-01-25 02:59
Specify an exact fork block number via 
`--fork.blockNumber` and let me know how that goes for you.

Does BSC support the London hardfork?

**Comment by NikZak** [comment] 2022-01-25 03:37
Thanks for replying so fast

Regarding London hardfork - bsc has implemented a [similar mechanism](https://github.com/binance-chain/BEPs/commit/3d4fae6715edd907f09a1e49f2ca51c34f2f14fc) to EIP-1559 but technical details may differ.

Regarding the blockNumber, I tried before but in different notation (with a @xxxxxxx in the end of the url). I tried just now (with an archive node) and still got stopped. Supposedly this error
```
ganache_1    | 
ganache_1    | <--- Last few GCs --->
ganache_1    | 
ganache_1    | [1:0x45312c0]   128765 ms: Scavenge 267.4 (278.2) -> 264.4 (279.4) MB, 14.5 / 0.0 ms  (average mu = 0.998, current mu = 0.998) allocation failure 
ganache_1    | [1:0x45312c0]   128879 ms: Scavenge 269.3 (279.8) -> 266.3 (282.1) MB, 17.7 / 0.0 ms  (average mu = 0.998, current mu = 0.998) allocation failure 
ganache_1    | [1:0x45312c0]   129055 ms: Scavenge 272.6 (283.6) -> 268.9 (284.6) MB, 20.9 / 0.0 ms  (average mu = 0.998, current mu = 0.998) allocation failure 
ganache_1    | 
ganache_1    | 
ganache_1    | <--- JS stacktrace --->
ganache_1    | 
ganache_1    | FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
ganache_1    |  1: 0xa25510 node::Abort() [/usr/local/bin/node]
ganache_1    |  2: 0x9664d3 node::FatalError(char const*, char const*) [/usr/local/bin/node]
ganache_1    |  3: 0xb9a8ee v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
ganache_1    |  4: 0xb9ac67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
ganache_1    |  5: 0xd56cd5  [/usr/local/bin/node]
ganache_1    |  6: 0xd96927  [/usr/local/bin/node]
ganache_1    |  7: 0xda8061 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
ganache_1    |  8: 0xd64328 v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
ganache_1    |  9: 0xd65e18 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
ganache_1    | 10: 0xd67d55 v8::internal::Heap::HandleGCRequest() [/usr/local/bin/node]
ganache_1    | 11: 0xd0e267 v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
ganache_1    | 12: 0x107f87a v8::internal::Runtime_StackGuardWithGap(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
ganache_1    | 13: 0x1426939  [/usr/local/bin/node]
ganache_1    | qemu: uncaught target signal 6 (Aborted) - core dumped

```

**Comment by davidmurdoch** [comment] 2022-01-25 13:23
Ah, I wonder if this is a Mac M1 issue. Can you provide complete reproduction steps?

**Comment by gnidan** [comment] 2022-01-26 19:22
Just adding this comment to note that you might observe different results if you run the Node.js native build, rather than Docker. (Since Docker runs Intel architecture inside M1, the increased virtualization complexity might be causing the trouble here).

But please do let us know how to reproduce so we can get to the bottom of it (since not using Docker isn't a real fix :)

**Comment by lsqproduction** [comment] 2022-03-08 20:44
Closing for issue maintenance.

**Closed as completed by lsqproduction** 2022-03-08 20:44 UTC
Labels: needs investigated
