### ISSUE TITLE
TypeError: r.URL is not a constructor

### ISSUE THREAD

**Issue by Thankgod20** [ConsenSys-archive/ganache#2539] opened 2022-03-06 21:48 UTC
I am using ganache cdn and when i call the fork option i get these errors

`Uncaught TypeError: r.URL is not a constructor
    at Object.normalize (ganache:2)
    at fill (ganache:2)
    at ganache:2
    at Array.forEach (<anonymous>)
    at OptionsConfig.normalize (ganache:2)
    at new EthereumProvider (ganache:2)
    at new Connector (ganache:2)
    at GetConnector (ganache:2)
    at Object.initialize (ganache:2)
    at Object.provider (ganache:2)`

here is the javascript code

`
<script src="https://cdn.jsdelivr.net/npm/ganache@7.0.2/dist/web/ganache.min.js"></script>
    <script>
        
        const options = {"fork":"https://bsc.getblock.io/mainnet/?api_key=<MY-API-KEY"}; 
        const provider = Ganache.provider(options);
    </script>
`
Any ideas on how to resolve these issue

**Comment by linzof** [comment] 2022-03-06 22:33
This line should be the cause

> const options = {"fork":"https://bsc.getblock.io/mainnet/?api_key=<MY-API-KEY"}; 


I am not sure how the rest of environment is set up. 

Since you are in js, you should use a template literal for concatenating strings and variables. 

[Template literals (Template strings)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

**Comment by davidmurdoch** [comment] 2022-03-07 00:09
Forking is not yet supported in the browser.

**Comment by lsqproduction** [comment] 2022-03-08 20:27
@Thankgod20 Thank you for letting us know. Closing this as a duplicate of #1245

**Closed as completed by lsqproduction** 2022-03-08 20:27 UTC
