### ISSUE TITLE
Simulating transactions on Ganache v7 fork throws insufficient funds error

### ISSUE THREAD

**Issue by haseebrabbani** [ConsenSys-archive/ganache#2162] opened 2022-01-23 10:45 UTC
hey there, appreciate your work on this amazing tool! when trying to integrate the latest version (ganache 7.0.0) into my previously working code (which used ganache-core 2.13.2) I am seeing some non-deterministic behaviour. Sometimes when simulating a transaction on a fork it will throw an `insufficient funds for intrinsic transaction cost` error. But other times, running the exact same code will work as expected. Here is what I am doing:

```
const provider = new ethers.providers.Web3Provider(ganache.provider({
    fork: {
      url: MY_INFURA_URL,
      blockNumber: SOME_BLOCK_NUMBER
    },
    wallet: {
      unlockedAccounts: [USER_ADDRESS]
    }
  }) as any)
const tetherContract = new ethers.Contract(TETHER_ADDRESS, TETHER_ABI, provider.getSigner(USER_ADDRESS))
const userTetherBalance = await tetherContract.balanceOf(USER_ADDRESS)
const tx = await tetherContract.transfer(USER2_ADDRESS, userTetherBalance) //<---- throws error here
```

**Comment by MicaiahReid** [comment] 2022-01-24 21:00
Hi @haseebrabbani, thanks for opening this issue. We're investigating this now. Is there any chance you could send a repo to help us reproduce this?

**Comment by haseebrabbani** [comment] 2022-01-26 10:02
@MicaiahReid for sure, here is a repo to reproduce: https://github.com/haseebrabbani/ganache-v7-forking-issue-repro

i'm simulating the transaction on a fork over a fixed range of 10 blocks. it seems that the error is thrown on the same blocks everytime. when i initially encountered this issue i was running it on increasing block numbers which made it appear non-deterministic

**Comment by MicaiahReid** [comment] 2022-01-26 14:53
@haseebrabbani This is perfect, thank you! We're looking into this now.

**Comment by MicaiahReid** [comment] 2022-01-27 02:16
Hi @haseebrabbani, we did some looking into this and think there's a combination of factors contributing to the issue. If you change your `transfer` call to include a `maxFeePerGas`, as follows:
```JavaScript
const tx = await tetherContract.transfer(
  USER2_ADDRESS,
  userTetherBalance,
  { maxFeePerGas: 90417983619 }
);
```
all of the transfers work. Whenever you fork from a block, the new "latest" block is used to set the `baseFeePerGas` of the next block. When no gas information is specified on a transaction, the default base fee is set by Ganache. This is an expensive gas premium because it ensures it will make it onto the block - but you're overspending on gas in that case. So, this was leading to insufficient funds to perform the transfer.

We plan to improve upon this in a number of ways:
 - add the `eth_feeHistory` RPC method to help set those parameters (#1470)
 - add the option to set a configurable, static `baseFeePerGas` #1573 

@haseebrabbani Let me know if the above fix doesn't work for you and we can investigate further. If it does work, feel free to close this issue!

**Comment by haseebrabbani** [comment] 2022-01-29 11:27
Appreciate the explanation! However, since this code will be client-facing I wouldn't want to use this workaround (and possibly link to this issue in a comment to explain why I'm setting `maxFeePerGas`). As such, I will hold off on integrating Ganache v7 and stick to `ganache-core` for the time being until a longer-term fix is implemented. Ideally, since users did not have to set this parameter before, they shouldn't have to set it in the latest version either

**Comment by davidmurdoch** [comment] 2022-01-29 15:12
If you want the revert to ganache-core's gas behavior and you don't care about type 2 transactions (eip-1559) you can set the hardfork option to `"berlin"`, or even back to `istanbul`.

**Comment by cds-amal** [comment] 2022-02-02 19:22
We're closing since it's working as intended. Please subscribe to the linked issues above to track progress.

**Closed as completed by cds-amal** 2022-02-02 19:22 UTC
Labels: awaiting response
