### ISSUE TITLE
Websocket logs subscription not supported by Geth Client

### ISSUE THREAD

**Issue by Ruj89** [ConsenSys-archive/ganache#2206] opened 2022-01-26 21:37 UTC
Platform: node:lts-alpine Docker image 
Ganache: v7.0.0
Node: v16.13.2
npm: 8.1.2
Go: 1.17.4
go-ethereum: v1.10.15

Description:

When I receive a log, after a subscription, the go-ethereum library try to send through a chan the Log typed object, but it cannot marshal the Ganache websocket message:

`json: cannot unmarshal array into Go value of type types.Log`

Steps to reproduce:
1. Deploy a smart contract;
2. Listen to the ganache ws endpoint for a event with a Geth client;
2. Execute a smart contract method that calls an event.

Expected result:
The Ganache WS server sends a canonical event message JSON object to Geth client.

Actual result:
The Ganache WS server sends an array of objects to Geth client.

Notes:
On Ganache CLI v6.12.2 the JSON event message was correctly parsed.

**Comment by davidmurdoch** [comment] 2022-01-26 22:00
Hi, thanks for opening the issue. We'll look into it!

**Comment by ndzik** [comment] 2022-02-01 14:58
Just for completeness and because I just encountered this issue: I can confirm this.

`json: cannot unmarshal array into Go value of type types.Log` errors for subscriptions with Ganache: `v7.0.1`.

I can also confirm that Ganache CLI `v6.12.2` works as expected for the time being (:

**Comment by davidmurdoch** [comment] 2022-02-01 15:37
@ndzik Thanks for the additional confirmation. We've found the root cause and are working on a fix now.

**Comment by MicaiahReid** [comment] 2022-02-03 20:58
This should be fixed in v7.0.2!

**Closed as completed by MicaiahReid** 2022-02-03 20:58 UTC
Labels: bug, priority1 🚨
