### ISSUE TITLE
`evm_setTime` doesn't work correctly with `miner.timestampIncrement`

### ISSUE THREAD

**Issue by jeffsmale90** [ConsenSys-archive/ganache#3330] opened 2022-07-05 02:15 UTC
When using `miner.timestampIncrement`, calling `evm_setTime` can result in unexpected values, and potentially with an error being thrown.

This is because the `timeAdjustment` is applied to the previous blocktime, so this offset is applied for every block that is mined.

With the following example, the initial block is mined correctly, as is the first block after setting the time, but subsequent blocks will have a descending block time, until the value becomes negative.

```javascript
const p = await getProvider({
  miner: {timestampIncrement: 1},
  chain: {time : 10000}
});

const mineAndShowBlock = async () => {
  await p.send("evm_mine");
  const {number, timestamp} = await p.send("eth_getBlockByNumber", ["latest"]);

  console.log({number, timestamp: Quantity.toNumber(timestamp)});  
}
await mineAndShowBlock();

await p.send("evm_setTime", [5000]);

while(true) {
  await mineAndShowBlock();
}
```

```
{ number: '0x1', timestamp: 11 }
{ number: '0x2', timestamp: 6 }
{ number: '0x3', timestamp: 1 }

Error: Cannot wrap a negative value as a json-rpc type
```

**Comment by jeffsmale90** [comment] 2022-08-07 23:09
Turns out this is a duplicate of #3265, closing as such.

**Comment by davidmurdoch** [comment] 2022-08-18 18:50
Reopening, I don't think this is a duplicate of #3265 as that one is about `clock` mode.

**Closed as completed** 2022-08-21 21:42 UTC
