### ISSUE TITLE
Add a way to create or modify arbitrary accounts and storage

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#1889] opened 2021-12-23 01:16 UTC
We can already create empty accounts, and set their nonce*, but we can't set their balance, code, or storage.

\* Related: https://github.com/trufflesuite/ganache/issues/1646

**Comment by rmeissner** [comment] 2022-02-10 13:07
This issue seems to be a partial duplicate of https://github.com/trufflesuite/ganache/issues/649

**Comment by MicaiahReid** [comment] 2022-04-13 13:55
Implemented by #2337.

**Closed as completed by MicaiahReid** 2022-04-13 13:55 UTC
Labels: enhancement, priority2 ⚠️
